@{
  '7-Zip'             = 'HKCU\Software\7-Zip'
  'AutoHotkey'        = 'HKCU\Software\AutoHotkey'
  'Console'           = 'HKCU\Console'
  'International'     = 'HKCU\Control Panel\International'
  'Office.Access'     = 'HKCU\Software\Microsoft\Office\16.0\Access\Settings'
  'Office.Excel'      = 'HKCU\Software\Microsoft\Office\16.0\Excel\Options'
  'Office.OneNote'    = 'HKCU\Software\Microsoft\Office\16.0\OneNote\Options'
  'Office.Outlook'    = 'HKCU\Software\Microsoft\Office\16.0\Outlook\Options'
  'Office.PowerPoint' = 'HKCU\Software\Microsoft\Office\16.0\PowerPoint\Options'
  'Office.Word'       = 'HKCU\Software\Microsoft\Office\16.0\Word\Options'
  'PDF-XChange'       = 'HKCU\Software\Tracker Software'
  'SQLite'            = 'HKCU\Software\sqlitebrowser'
  'Subversion'        = 'HKCU\Software\Tigris.org\Subversion'
  'TortoiseGit'       = 'HKCU\Software\TortoiseGit'
  'TortoiseGitBlame'  = 'HKCU\Software\TortoiseGitBlame'
  'TortoiseGitMerge'  = 'HKCU\Software\TortoiseGitMerge'
  'TortoiseMerge'     = 'HKCU\Software\TortoiseMerge'
  'TortoiseSVN'       = 'HKCU\Software\TortoiseSVN'
  'VBA'               = 'HKCU\Software\Microsoft\VBA'
  'WinMerge'          = 'HKCU\Software\Thingamahoochie\WinMerge'
  'WSL'               = 'HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss'
}
